package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class ClassDomain extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.school_id
     * 创建时间 : 2018-06-04 10:00:16
     */
    private Long schoolId;

    /**
     * 年级 -- class.grade
     * 创建时间 : 2018-06-04 10:00:16
     */
    private Byte grade;

    /**
     * 班级号 -- class.class_no
     * 创建时间 : 2018-06-04 10:00:16
     */
    private Byte classNo;

    /**
     * 学生数量 -- class.student_num
     * 创建时间 : 2018-06-04 10:00:16
     */
    private Short studentNum;

    /**
     * 学期开始时间 -- class.term_start_time
     * 创建时间 : 2018-06-04 10:00:16
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date termStartTime;

    /**
     * 学期结束时间 -- class.term_end_time
     * 创建时间 : 2018-06-04 10:00:16
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date termEndTime;

    /**
     * 是否删除，0-否，1-是 -- class.del_flag
     * 创建时间 : 2018-06-04 10:00:16
     */
    private Boolean delFlag;

    /**
     * class表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-04 10:00:16
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 class.school_id的get方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * 数据字段 class.school_id的set方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * 数据字段 class.grade的get方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * 数据字段 class.grade的set方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * 数据字段 class.class_no的get方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public Byte getClassNo() {
        return classNo;
    }

    /**
     * 数据字段 class.class_no的set方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public void setClassNo(Byte classNo) {
        this.classNo = classNo;
    }

    /**
     * 数据字段 class.student_num的get方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public Short getStudentNum() {
        return studentNum;
    }

    /**
     * 数据字段 class.student_num的set方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public void setStudentNum(Short studentNum) {
        this.studentNum = studentNum;
    }

    /**
     * 数据字段 class.term_start_time的get方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public Date getTermStartTime() {
        return termStartTime;
    }

    /**
     * 数据字段 class.term_start_time的set方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public void setTermStartTime(Date termStartTime) {
        this.termStartTime = termStartTime;
    }

    /**
     * 数据字段 class.term_end_time的get方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public Date getTermEndTime() {
        return termEndTime;
    }

    /**
     * 数据字段 class.term_end_time的set方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public void setTermEndTime(Date termEndTime) {
        this.termEndTime = termEndTime;
    }

    /**
     * 数据字段 class.del_flag的get方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 class.del_flag的set方法
     * 创建时间 : 2018-06-04 10:00:16
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}