package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class ExerciseClass implements Serializable {
    /**
     * 习题班级关系表ID -- exercise_class.id
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Long id;

    /**
     * 习题表ID -- exercise_class.exercise_id
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Long exerciseId;

    /**
     * 老师班级表ID -- exercise_class.teacher_class_id
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Long teacherClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_class.create_time
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_class.update_time
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Date updateTime;

    /**
     * 1-删除 -- exercise_class.del_flag
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Boolean delFlag;

    /**
     * exercise_class表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-04 13:04:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 exercise_class.id的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 exercise_class.id的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 exercise_class.exercise_id的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Long getExerciseId() {
        return exerciseId;
    }

    /**
     * 数据字段 exercise_class.exercise_id的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setExerciseId(Long exerciseId) {
        this.exerciseId = exerciseId;
    }

    /**
     * 数据字段 exercise_class.teacher_class_id的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Long getTeacherClassId() {
        return teacherClassId;
    }

    /**
     * 数据字段 exercise_class.teacher_class_id的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setTeacherClassId(Long teacherClassId) {
        this.teacherClassId = teacherClassId;
    }

    /**
     * 数据字段 exercise_class.create_time的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 exercise_class.create_time的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 exercise_class.update_time的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 exercise_class.update_time的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 数据字段 exercise_class.del_flag的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 exercise_class.del_flag的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}