package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class FileNotes extends BaseDomain {

    /**
     * 一个子资源可以生成多个笔记资源 -- file_notes.child_resource_id
     * 创建时间 : 2018-06-13 19:14:58
     */
    private Long childResourceId;

    /**
     * 笔记文件名 -- file_notes.note_name
     * 创建时间 : 2018-06-13 19:14:58
     */
    private String noteName;

    /**
     * 笔记文件类型，2-图片 -- file_notes.note_type
     * 创建时间 : 2018-06-13 19:14:58
     */
    private Byte noteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_notes.note_content
     * 创建时间 : 2018-06-13 19:14:58
     */
    private String noteContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_notes.del_flag
     * 创建时间 : 2018-06-13 19:14:58
     */
    private Boolean delFlag;

    /**
     * file_notes表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-13 19:14:58
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 file_notes.child_resource_id的get方法 
     * 创建时间 : 2018-06-13 19:14:58
     */
    public Long getChildResourceId() {
        return childResourceId;
    }

    /**
     * 数据字段 file_notes.child_resource_id的set方法
     * 创建时间 : 2018-06-13 19:14:58
     */
    public void setChildResourceId(Long childResourceId) {
        this.childResourceId = childResourceId;
    }

    /**
     * 数据字段 file_notes.note_name的get方法 
     * 创建时间 : 2018-06-13 19:14:58
     */
    public String getNoteName() {
        return noteName;
    }

    /**
     * 数据字段 file_notes.note_name的set方法
     * 创建时间 : 2018-06-13 19:14:58
     */
    public void setNoteName(String noteName) {
        this.noteName = noteName == null ? null : noteName.trim();
    }

    /**
     * 数据字段 file_notes.note_type的get方法 
     * 创建时间 : 2018-06-13 19:14:58
     */
    public Byte getNoteType() {
        return noteType;
    }

    /**
     * 数据字段 file_notes.note_type的set方法
     * 创建时间 : 2018-06-13 19:14:58
     */
    public void setNoteType(Byte noteType) {
        this.noteType = noteType;
    }

    /**
     * 数据字段 file_notes.note_content的get方法 
     * 创建时间 : 2018-06-13 19:14:58
     */
    public String getNoteContent() {
        return noteContent;
    }

    /**
     * 数据字段 file_notes.note_content的set方法
     * 创建时间 : 2018-06-13 19:14:58
     */
    public void setNoteContent(String noteContent) {
        this.noteContent = noteContent == null ? null : noteContent.trim();
    }

    /**
     * 数据字段 file_notes.del_flag的get方法 
     * 创建时间 : 2018-06-13 19:14:58
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 file_notes.del_flag的set方法
     * 创建时间 : 2018-06-13 19:14:58
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}