package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class PackageResourceNote extends BaseDomain{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_resource_note.package_class_id
     * 创建时间 : 2018-07-19 22:05:33
     */
    private Long packageClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_resource_note.resource_id
     * 创建时间 : 2018-07-19 22:05:33
     */
    private Long resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_resource_note.child_resource_id
     * 创建时间 : 2018-07-19 22:05:33
     */
    private Long childResourceId;

    /**
     * 笔记文件名 -- package_resource_note.note_name
     * 创建时间 : 2018-07-19 22:05:33
     */
    private String noteName;

    /**
     * 笔记文件类型，2-图片 -- package_resource_note.note_type
     * 创建时间 : 2018-07-19 22:05:33
     */
    private Byte noteType;

    /**
     * 笔记内容 -- package_resource_note.note_content
     * 创建时间 : 2018-07-19 22:05:33
     */
    private String noteContent;

    /**
     * 对教师是否显示，0-否，1-是 -- package_resource_note.teacher_show_flag
     * 创建时间 : 2018-07-19 22:05:33
     */
    private Short teacherShowFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_resource_note.del_flag
     * 创建时间 : 2018-07-19 22:05:33
     */
    private Boolean delFlag;

    /**
     * package_resource_note表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-19 22:05:33
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 package_resource_note.package_class_id的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public Long getPackageClassId() {
        return packageClassId;
    }

    /**
     * 数据字段 package_resource_note.package_class_id的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setPackageClassId(Long packageClassId) {
        this.packageClassId = packageClassId;
    }

    /**
     * 数据字段 package_resource_note.resource_id的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * 数据字段 package_resource_note.resource_id的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * 数据字段 package_resource_note.child_resource_id的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public Long getChildResourceId() {
        return childResourceId;
    }

    /**
     * 数据字段 package_resource_note.child_resource_id的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setChildResourceId(Long childResourceId) {
        this.childResourceId = childResourceId;
    }

    /**
     * 数据字段 package_resource_note.note_name的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public String getNoteName() {
        return noteName;
    }

    /**
     * 数据字段 package_resource_note.note_name的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setNoteName(String noteName) {
        this.noteName = noteName == null ? null : noteName.trim();
    }

    /**
     * 数据字段 package_resource_note.note_type的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public Byte getNoteType() {
        return noteType;
    }

    /**
     * 数据字段 package_resource_note.note_type的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setNoteType(Byte noteType) {
        this.noteType = noteType;
    }

    /**
     * 数据字段 package_resource_note.note_content的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public String getNoteContent() {
        return noteContent;
    }

    /**
     * 数据字段 package_resource_note.note_content的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setNoteContent(String noteContent) {
        this.noteContent = noteContent == null ? null : noteContent.trim();
    }

    /**
     * 数据字段 package_resource_note.teacher_show_flag的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public Short getTeacherShowFlag() {
        return teacherShowFlag;
    }

    /**
     * 数据字段 package_resource_note.teacher_show_flag的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setTeacherShowFlag(Short teacherShowFlag) {
        this.teacherShowFlag = teacherShowFlag;
    }

    /**
     * 数据字段 package_resource_note.del_flag的get方法 
     * 创建时间 : 2018-07-19 22:05:33
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 package_resource_note.del_flag的set方法
     * 创建时间 : 2018-07-19 22:05:33
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}