package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class PackageExercise implements Serializable {
    /**
     * 包与习题关系表ID -- package_exercise.id
     * 创建时间 : 2018-07-05 22:01:17
     */
    private Long id;

    /**
     * package_info表id -- package_exercise.package_class_id
     * 创建时间 : 2018-07-05 22:01:17
     */
    private Long packageClassId;

    /**
     * 习题ID -- package_exercise.exercise_id
     * 创建时间 : 2018-07-05 22:01:17
     */
    private Long exerciseId;

    /**
     * 该资源在该班级的状态，0-未开始，1-已结束 -- package_exercise.status
     * 创建时间 : 2018-07-05 22:01:17
     */
    private Byte status;

    /**
     * 预留 -- package_exercise.remark
     * 创建时间 : 2018-07-05 22:01:17
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_exercise.create_time
     * 创建时间 : 2018-07-05 22:01:17
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_exercise.update_time
     * 创建时间 : 2018-07-05 22:01:17
     */
    private Date updateTime;

    /**
     * 1-删除  0-未删除 -- package_exercise.del_flag
     * 创建时间 : 2018-07-05 22:01:17
     */
    private Boolean delFlag;

    /**
     * package_exercise表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-05 22:01:17
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 package_exercise.id的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 package_exercise.id的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 package_exercise.package_class_id的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public Long getPackageClassId() {
        return packageClassId;
    }

    /**
     * 数据字段 package_exercise.package_class_id的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setPackageClassId(Long packageClassId) {
        this.packageClassId = packageClassId;
    }

    /**
     * 数据字段 package_exercise.exercise_id的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public Long getExerciseId() {
        return exerciseId;
    }

    /**
     * 数据字段 package_exercise.exercise_id的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setExerciseId(Long exerciseId) {
        this.exerciseId = exerciseId;
    }

    /**
     * 数据字段 package_exercise.status的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 数据字段 package_exercise.status的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 数据字段 package_exercise.remark的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 数据字段 package_exercise.remark的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 数据字段 package_exercise.create_time的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 package_exercise.create_time的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 package_exercise.update_time的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 package_exercise.update_time的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 数据字段 package_exercise.del_flag的get方法 
     * 创建时间 : 2018-07-05 22:01:17
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 package_exercise.del_flag的set方法
     * 创建时间 : 2018-07-05 22:01:17
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}