package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

public class PackageInfo extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_info.teacher_id
     * 创建时间 : 2018-06-30 18:33:52
     */
    private Long teacherId;

    /**
     * 包名 -- package_info.package_name
     * 创建时间 : 2018-06-30 18:33:52
     */
    private String packageName;

    /**
     * 教师班级关系id -- package_info.teacher_class_id
     * 创建时间 : 2018-06-30 18:33:52
     */
    private Long teacherClassId;

    /**
     * package_info表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-30 18:33:52
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 package_info.teacher_id的get方法
     * 创建时间 : 2018-06-30 18:33:52
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * 数据字段 package_info.teacher_id的set方法
     * 创建时间 : 2018-06-30 18:33:52
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * 数据字段 package_info.package_name的get方法
     * 创建时间 : 2018-06-30 18:33:52
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * 数据字段 package_info.package_name的set方法
     * 创建时间 : 2018-06-30 18:33:52
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * 数据字段 package_info.teacher_class_id的get方法
     * 创建时间 : 2018-06-30 18:33:52
     */
    public Long getTeacherClassId() {
        return teacherClassId;
    }

    /**
     * 数据字段 package_info.teacher_class_id的set方法
     * 创建时间 : 2018-06-30 18:33:52
     */
    public void setTeacherClassId(Long teacherClassId) {
        this.teacherClassId = teacherClassId;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}