package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class PackageClass extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_class.package_id
     * 创建时间 : 2018-06-13 21:14:34
     */
    private Long packageId;

    /**
     * 老师班级关系表的id -- package_class.teacher_class_id
     * 创建时间 : 2018-06-13 21:14:34
     */
    private Long teacherClassId;

    /**
     * 资源包在班级里的状态，0-未上课，1-已上课 -- package_class.status
     * 创建时间 : 2018-06-13 21:14:34
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_class.del_flag
     * 创建时间 : 2018-06-13 21:14:34
     */
    private Boolean delFlag;

    /**
     * package_class表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-13 21:14:34
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 package_class.package_id的get方法 
     * 创建时间 : 2018-06-13 21:14:34
     */
    public Long getPackageId() {
        return packageId;
    }

    /**
     * 数据字段 package_class.package_id的set方法
     * 创建时间 : 2018-06-13 21:14:34
     */
    public void setPackageId(Long packageId) {
        this.packageId = packageId;
    }

    /**
     * 数据字段 package_class.teacher_class_id的get方法 
     * 创建时间 : 2018-06-13 21:14:34
     */
    public Long getTeacherClassId() {
        return teacherClassId;
    }

    /**
     * 数据字段 package_class.teacher_class_id的set方法
     * 创建时间 : 2018-06-13 21:14:34
     */
    public void setTeacherClassId(Long teacherClassId) {
        this.teacherClassId = teacherClassId;
    }

    /**
     * 数据字段 package_class.status的get方法 
     * 创建时间 : 2018-06-13 21:14:34
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 数据字段 package_class.status的set方法
     * 创建时间 : 2018-06-13 21:14:34
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 数据字段 package_class.del_flag的get方法 
     * 创建时间 : 2018-06-13 21:14:34
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 package_class.del_flag的set方法
     * 创建时间 : 2018-06-13 21:14:34
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}