package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class StatisticsInfo extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_info.unit_test_exercise_id
     * 创建时间 : 2018-07-13 13:54:06
     */
    private Long unitTestExerciseId;

    /**
     * 已提交的人数 -- statistics_info.submit_num
     * 创建时间 : 2018-07-13 13:54:06
     */
    private Integer submitNum;

    /**
     * 未提交人数 -- statistics_info.un_submit_num
     * 创建时间 : 2018-07-13 13:54:06
     */
    private Integer unSubmitNum;

    /**
     * 已提交未选择人数 -- statistics_info.submit_no_select
     * 创建时间 : 2018-07-13 13:54:06
     */
    private Integer submitNoSelect;

    /**
     * 答对人数 -- statistics_info.right_num
     * 创建时间 : 2018-07-13 13:54:06
     */
    private Integer rightNum;

    /**
     * 答错人数 -- statistics_info.wrong_num
     * 创建时间 : 2018-07-13 13:54:06
     */
    private Integer wrongNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics_info.options
     * 创建时间 : 2018-07-13 13:54:06
     */
    private String options;

    /**
     * statistics_info表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-13 13:54:06
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 statistics_info.unit_test_exercise_id的get方法 
     * 创建时间 : 2018-07-13 13:54:06
     */
    public Long getUnitTestExerciseId() {
        return unitTestExerciseId;
    }

    /**
     * 数据字段 statistics_info.unit_test_exercise_id的set方法
     * 创建时间 : 2018-07-13 13:54:06
     */
    public void setUnitTestExerciseId(Long unitTestExerciseId) {
        this.unitTestExerciseId = unitTestExerciseId;
    }

    /**
     * 数据字段 statistics_info.submit_num的get方法 
     * 创建时间 : 2018-07-13 13:54:06
     */
    public Integer getSubmitNum() {
        return submitNum;
    }

    /**
     * 数据字段 statistics_info.submit_num的set方法
     * 创建时间 : 2018-07-13 13:54:06
     */
    public void setSubmitNum(Integer submitNum) {
        this.submitNum = submitNum;
    }

    /**
     * 数据字段 statistics_info.un_submit_num的get方法 
     * 创建时间 : 2018-07-13 13:54:06
     */
    public Integer getUnSubmitNum() {
        return unSubmitNum;
    }

    /**
     * 数据字段 statistics_info.un_submit_num的set方法
     * 创建时间 : 2018-07-13 13:54:06
     */
    public void setUnSubmitNum(Integer unSubmitNum) {
        this.unSubmitNum = unSubmitNum;
    }

    /**
     * 数据字段 statistics_info.submit_no_select的get方法 
     * 创建时间 : 2018-07-13 13:54:06
     */
    public Integer getSubmitNoSelect() {
        return submitNoSelect;
    }

    /**
     * 数据字段 statistics_info.submit_no_select的set方法
     * 创建时间 : 2018-07-13 13:54:06
     */
    public void setSubmitNoSelect(Integer submitNoSelect) {
        this.submitNoSelect = submitNoSelect;
    }

    /**
     * 数据字段 statistics_info.right_num的get方法 
     * 创建时间 : 2018-07-13 13:54:06
     */
    public Integer getRightNum() {
        return rightNum;
    }

    /**
     * 数据字段 statistics_info.right_num的set方法
     * 创建时间 : 2018-07-13 13:54:06
     */
    public void setRightNum(Integer rightNum) {
        this.rightNum = rightNum;
    }

    /**
     * 数据字段 statistics_info.wrong_num的get方法 
     * 创建时间 : 2018-07-13 13:54:06
     */
    public Integer getWrongNum() {
        return wrongNum;
    }

    /**
     * 数据字段 statistics_info.wrong_num的set方法
     * 创建时间 : 2018-07-13 13:54:06
     */
    public void setWrongNum(Integer wrongNum) {
        this.wrongNum = wrongNum;
    }

    /**
     * 数据字段 statistics_info.options的get方法 
     * 创建时间 : 2018-07-13 13:54:06
     */
    public String getOptions() {
        return options;
    }

    /**
     * 数据字段 statistics_info.options的set方法
     * 创建时间 : 2018-07-13 13:54:06
     */
    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}