package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Student extends BaseDomain {

    /**
     * 班级id -- student.class_id
     * 创建时间 : 2018-06-03 15:54:05
     */
    private Long classId;

    /**
     * 学校id -- student.school_id
     * 创建时间 : 2018-06-03 15:54:05
     */
    private Long schoolId;

    /**
     * 学生号 -- student.student_no
     * 创建时间 : 2018-06-03 15:54:05
     */
    private String studentNo;

    /**
     * 学生姓名 -- student.student_name
     * 创建时间 : 2018-06-03 15:54:05
     */
    private String studentName;

    /**
     * 头像地址 -- student.head_img
     * 创建时间 : 2018-06-04 14:03:20
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     * 创建时间 : 2018-06-03 15:54:05
     */
    private String password;

    /**
     * 家长手机号 -- student.parent_phone
     * 创建时间 : 2018-06-03 15:54:05
     */
    private String parentPhone;

    /**
     * 入学时间 -- student.begin_time
     * 创建时间 : 2018-06-03 15:54:05
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date beginTime;

    /**
     *  年龄 -- student.age
     * 创建时间 : 2018-06-03 15:54:05
     */
    private Byte age;

    /**
     * 是否删除，0-否，1-是 -- student.del_flag
     * 创建时间 : 2018-06-03 15:54:05
     */
    private Boolean delFlag;

    /**
     * student表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-03 15:54:05
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 student.class_id的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * 数据字段 student.class_id的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * 数据字段 student.school_id的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * 数据字段 student.school_id的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * 数据字段 student.student_no的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * 数据字段 student.student_no的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * 数据字段 student.student_name的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * 数据字段 student.student_name的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * 数据字段 student.head_img的get方法
     * 创建时间 : 2018-06-04 14:03:20
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * 数据字段 student.head_img的set方法
     * 创建时间 : 2018-06-04 14:03:20
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * 数据字段 student.password的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public String getPassword() {
        return password;
    }

    /**
     * 数据字段 student.password的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * 数据字段 student.parent_phone的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public String getParentPhone() {
        return parentPhone;
    }

    /**
     * 数据字段 student.parent_phone的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setParentPhone(String parentPhone) {
        this.parentPhone = parentPhone == null ? null : parentPhone.trim();
    }

    /**
     * 数据字段 student.begin_time的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * 数据字段 student.begin_time的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * 数据字段 student.age的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public Byte getAge() {
        return age;
    }

    /**
     * 数据字段 student.age的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * 数据字段 student.del_flag的get方法 
     * 创建时间 : 2018-06-03 15:54:05
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 student.del_flag的set方法
     * 创建时间 : 2018-06-03 15:54:05
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}