package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class StudentCollectExercise implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_collect_exercise.id
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Long id;

    /**
     * 学科ID -- student_collect_exercise.subject_id
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Long subjectId;

    /**
     * 学生ID -- student_collect_exercise.student_id
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Long studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_collect_exercise.package_class_id
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Long packageClassId;

    /**
     * 习题ID -- student_collect_exercise.exercise_id
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Long exerciseId;

    /**
     * 学生答案 -- student_collect_exercise.student_answer
     * 创建时间 : 2018-07-16 17:11:48
     */
    private String studentAnswer;

    /**
     * 答题结果，1-答对，2-答错 -- student_collect_exercise.answer_result
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Short answerResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_collect_exercise.create_time
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_collect_exercise.update_time
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Date updateTime;

    /**
     * 0-存在,1-删除 -- student_collect_exercise.del_flag
     * 创建时间 : 2018-07-16 17:11:48
     */
    private Boolean delFlag;

    /**
     * student_collect_exercise表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-16 17:11:48
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 student_collect_exercise.id的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 student_collect_exercise.id的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 student_collect_exercise.subject_id的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * 数据字段 student_collect_exercise.subject_id的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * 数据字段 student_collect_exercise.student_id的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * 数据字段 student_collect_exercise.student_id的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * 数据字段 student_collect_exercise.package_class_id的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Long getPackageClassId() {
        return packageClassId;
    }

    /**
     * 数据字段 student_collect_exercise.package_class_id的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setPackageClassId(Long packageClassId) {
        this.packageClassId = packageClassId;
    }

    /**
     * 数据字段 student_collect_exercise.exercise_id的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Long getExerciseId() {
        return exerciseId;
    }

    /**
     * 数据字段 student_collect_exercise.exercise_id的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setExerciseId(Long exerciseId) {
        this.exerciseId = exerciseId;
    }

    /**
     * 数据字段 student_collect_exercise.student_answer的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public String getStudentAnswer() {
        return studentAnswer;
    }

    /**
     * 数据字段 student_collect_exercise.student_answer的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setStudentAnswer(String studentAnswer) {
        this.studentAnswer = studentAnswer == null ? null : studentAnswer.trim();
    }

    /**
     * 数据字段 student_collect_exercise.answer_result的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Short getAnswerResult() {
        return answerResult;
    }

    /**
     * 数据字段 student_collect_exercise.answer_result的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setAnswerResult(Short answerResult) {
        this.answerResult = answerResult;
    }

    /**
     * 数据字段 student_collect_exercise.create_time的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 student_collect_exercise.create_time的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 student_collect_exercise.update_time的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 student_collect_exercise.update_time的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 数据字段 student_collect_exercise.del_flag的get方法 
     * 创建时间 : 2018-07-16 17:11:48
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 student_collect_exercise.del_flag的set方法
     * 创建时间 : 2018-07-16 17:11:48
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}