package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class StudentExerciseSubmit extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_exercise_submit.student_id
     * 创建时间 : 2018-07-12 17:03:48
     */
    private Long studentId;

    /**
     * unit_test_exercises表id -- student_exercise_submit.unit_test_exercise_id
     * 创建时间 : 2018-07-12 17:03:48
     */
    private Long unitTestExerciseId;

    /**
     * 学生答案 -- student_exercise_submit.student_answer
     * 创建时间 : 2018-07-12 17:03:48
     */
    private String studentAnswer;

    /**
     * 答题结果，1-答对，2-答错 -- student_exercise_submit.answer_result
     * 创建时间 : 2018-07-12 17:03:48
     */
    private Short answerResult;

    /**
     * 耗时，单位秒 -- student_exercise_submit.cost_time
     * 创建时间 : 2018-07-12 17:03:48
     */
    private Integer costTime;

    /**
     * student_exercise_submit表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-12 17:03:48
     */
    private static final long serialVersionUID = 1L;


    /**
     * 数据字段 student_exercise_submit.student_id的get方法 
     * 创建时间 : 2018-07-12 17:03:48
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * 数据字段 student_exercise_submit.student_id的set方法
     * 创建时间 : 2018-07-12 17:03:48
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * 数据字段 student_exercise_submit.unit_test_exercise_id的get方法 
     * 创建时间 : 2018-07-12 17:03:48
     */
    public Long getUnitTestExerciseId() {
        return unitTestExerciseId;
    }

    /**
     * 数据字段 student_exercise_submit.unit_test_exercise_id的set方法
     * 创建时间 : 2018-07-12 17:03:48
     */
    public void setUnitTestExerciseId(Long unitTestExerciseId) {
        this.unitTestExerciseId = unitTestExerciseId;
    }

    /**
     * 数据字段 student_exercise_submit.student_answer的get方法 
     * 创建时间 : 2018-07-12 17:03:48
     */
    public String getStudentAnswer() {
        return studentAnswer;
    }

    /**
     * 数据字段 student_exercise_submit.student_answer的set方法
     * 创建时间 : 2018-07-12 17:03:48
     */
    public void setStudentAnswer(String studentAnswer) {
        this.studentAnswer = studentAnswer == null ? null : studentAnswer.trim();
    }

    /**
     * 数据字段 student_exercise_submit.answer_result的get方法 
     * 创建时间 : 2018-07-12 17:03:48
     */
    public Short getAnswerResult() {
        return answerResult;
    }

    /**
     * 数据字段 student_exercise_submit.answer_result的set方法
     * 创建时间 : 2018-07-12 17:03:48
     */
    public void setAnswerResult(Short answerResult) {
        this.answerResult = answerResult;
    }

    /**
     * 数据字段 student_exercise_submit.cost_time的get方法 
     * 创建时间 : 2018-07-12 17:03:48
     */
    public Integer getCostTime() {
        return costTime;
    }

    /**
     * 数据字段 student_exercise_submit.cost_time的set方法
     * 创建时间 : 2018-07-12 17:03:48
     */
    public void setCostTime(Integer costTime) {
        this.costTime = costTime;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}