package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class SystemMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.id
     * 创建时间 : 2018-06-02 22:58:40
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.parent_menu_id
     * 创建时间 : 2018-06-02 22:58:40
     */
    private Integer parentMenuId;

    /**
     * 菜单名 -- system_menu.menu_name
     * 创建时间 : 2018-06-02 22:58:40
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.menu_url
     * 创建时间 : 2018-06-02 22:58:40
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.create_time
     * 创建时间 : 2018-06-02 22:58:40
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu.update_time
     * 创建时间 : 2018-06-02 22:58:40
     */
    private Date updateTime;

    /**
     * system_menu表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-02 22:58:40
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 system_menu.id的get方法 
     * 创建时间 : 2018-06-02 22:58:40
     */
    public Integer getId() {
        return id;
    }

    /**
     * 数据字段 system_menu.id的set方法
     * 创建时间 : 2018-06-02 22:58:40
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 数据字段 system_menu.parent_menu_id的get方法 
     * 创建时间 : 2018-06-02 22:58:40
     */
    public Integer getParentMenuId() {
        return parentMenuId;
    }

    /**
     * 数据字段 system_menu.parent_menu_id的set方法
     * 创建时间 : 2018-06-02 22:58:40
     */
    public void setParentMenuId(Integer parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * 数据字段 system_menu.menu_name的get方法 
     * 创建时间 : 2018-06-02 22:58:40
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * 数据字段 system_menu.menu_name的set方法
     * 创建时间 : 2018-06-02 22:58:40
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * 数据字段 system_menu.menu_url的get方法 
     * 创建时间 : 2018-06-02 22:58:40
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * 数据字段 system_menu.menu_url的set方法
     * 创建时间 : 2018-06-02 22:58:40
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * 数据字段 system_menu.create_time的get方法 
     * 创建时间 : 2018-06-02 22:58:40
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 system_menu.create_time的set方法
     * 创建时间 : 2018-06-02 22:58:40
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 system_menu.update_time的get方法 
     * 创建时间 : 2018-06-02 22:58:40
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 system_menu.update_time的set方法
     * 创建时间 : 2018-06-02 22:58:40
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}