package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

public class TeacherCatalog extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_catalog.teacher_id
     * 创建时间 : 2018-06-04 14:20:38
     */
    private Long teacherId;

    /**
     * 父目录id -- teacher_catalog.parent_catalog_id
     * 创建时间 : 2018-06-04 14:20:38
     */
    private Long parentCatalogId;

    /**
     * 目录名 -- teacher_catalog.catalog_name
     * 创建时间 : 2018-06-04 14:20:38
     */
    private String catalogName;

    /**
     * 是否删除，0-否，1-是 -- teacher_catalog.del_flag
     * 创建时间 : 2018-06-04 14:20:38
     */
    private Boolean delFlag;

    /**
     * teacher_catalog表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-04 14:20:38
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 teacher_catalog.teacher_id的get方法 
     * 创建时间 : 2018-06-04 14:20:38
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * 数据字段 teacher_catalog.teacher_id的set方法
     * 创建时间 : 2018-06-04 14:20:38
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * 数据字段 teacher_catalog.parent_catalog_id的get方法 
     * 创建时间 : 2018-06-04 14:20:38
     */
    public Long getParentCatalogId() {
        return parentCatalogId;
    }

    /**
     * 数据字段 teacher_catalog.parent_catalog_id的set方法
     * 创建时间 : 2018-06-04 14:20:38
     */
    public void setParentCatalogId(Long parentCatalogId) {
        this.parentCatalogId = parentCatalogId;
    }

    /**
     * 数据字段 teacher_catalog.catalog_name的get方法 
     * 创建时间 : 2018-06-04 14:20:38
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * 数据字段 teacher_catalog.catalog_name的set方法
     * 创建时间 : 2018-06-04 14:20:38
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName == null ? null : catalogName.trim();
    }

    /**
     * 数据字段 teacher_catalog.del_flag的get方法 
     * 创建时间 : 2018-06-04 14:20:38
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 teacher_catalog.del_flag的set方法
     * 创建时间 : 2018-06-04 14:20:38
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}