package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class TeacherExercise implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_exercise.id
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Long id;

    /**
     * 教师ID -- teacher_exercise.teacher_id
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Long teacherId;

    /**
     * 习题ID -- teacher_exercise.exercise_id
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Long exerciseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_exercise.create_time
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_exercise.update_time
     * 创建时间 : 2018-07-04 13:04:26
     */
    private Date updateTime;

    /**
     * teacher_exercise表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-04 13:04:26
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 teacher_exercise.id的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 teacher_exercise.id的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 teacher_exercise.teacher_id的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * 数据字段 teacher_exercise.teacher_id的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * 数据字段 teacher_exercise.exercise_id的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Long getExerciseId() {
        return exerciseId;
    }

    /**
     * 数据字段 teacher_exercise.exercise_id的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setExerciseId(Long exerciseId) {
        this.exerciseId = exerciseId;
    }

    /**
     * 数据字段 teacher_exercise.create_time的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 teacher_exercise.create_time的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 teacher_exercise.update_time的get方法 
     * 创建时间 : 2018-07-04 13:04:26
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 teacher_exercise.update_time的set方法
     * 创建时间 : 2018-07-04 13:04:26
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}