package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

import java.io.Serializable;
import java.util.Date;

public class TeacherResource extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_resource.teacher_id
     * 创建时间 : 2018-06-06 19:11:47
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_resource.resource_id
     * 创建时间 : 2018-06-06 19:11:47
     */
    private Long resourceId;

    /**
     * 1-创建，2-被分享 -- teacher_resource.relationship
     * 创建时间 : 2018-06-06 19:11:47
     */
    private Byte relationship;

    /**
     * teacher_resource表的操作属性:serialVersionUID
     * 创建时间 : 2018-06-06 19:11:47
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 teacher_resource.teacher_id的get方法 
     * 创建时间 : 2018-06-06 19:11:47
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * 数据字段 teacher_resource.teacher_id的set方法
     * 创建时间 : 2018-06-06 19:11:47
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * 数据字段 teacher_resource.resource_id的get方法 
     * 创建时间 : 2018-06-06 19:11:47
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * 数据字段 teacher_resource.resource_id的set方法
     * 创建时间 : 2018-06-06 19:11:47
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * 数据字段 teacher_resource.relationship的get方法 
     * 创建时间 : 2018-06-06 19:11:47
     */
    public Byte getRelationship() {
        return relationship;
    }

    /**
     * 数据字段 teacher_resource.relationship的set方法
     * 创建时间 : 2018-06-06 19:11:47
     */
    public void setRelationship(Byte relationship) {
        this.relationship = relationship;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}