package com.booksroo.classroom.common.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

public class UnitTest extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_test.package_class_id
     * 创建时间 : 2018-07-12 13:49:55
     */
    private Long packageClassId;

    /**
     * 测试名称 -- unit_test.name
     * 创建时间 : 2018-07-12 13:49:55
     */
    private String name;

    /**
     * unit_test表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-12 13:49:55
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 unit_test.package_class_id的get方法 
     * 创建时间 : 2018-07-12 13:49:55
     */
    public Long getPackageClassId() {
        return packageClassId;
    }

    /**
     * 数据字段 unit_test.package_class_id的set方法
     * 创建时间 : 2018-07-12 13:49:55
     */
    public void setPackageClassId(Long packageClassId) {
        this.packageClassId = packageClassId;
    }

    /**
     * 数据字段 unit_test.name的get方法 
     * 创建时间 : 2018-07-12 13:49:55
     */
    public String getName() {
        return name;
    }

    /**
     * 数据字段 unit_test.name的set方法
     * 创建时间 : 2018-07-12 13:49:55
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}