package com.booksroo.classroom.common.domain;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang.builder.ReflectionToStringBuilder;

public class ExerciseDomain implements Serializable {
    /**
     * 习题ID -- exercise_info.id
     * 创建时间 : 2018-07-18 15:24:03
     */
    private Long id;

    /**
     * 创建人ID -- exercise_info.teacher_id
     * 创建时间 : 2018-07-18 15:24:03
     */
    private Long teacherId;

    /**
     * 习题类型（1.选择题 2.判断题 3.填空题 4.主观题） -- exercise_info.type
     * 创建时间 : 2018-07-18 15:24:03
     */
    private Byte type;

    /**
     * 习题图片地址 -- exercise_info.content_url
     * 创建时间 : 2018-07-18 15:24:03
     */
    private String contentUrl;

    /**
     * 习题分析图片地址 -- exercise_info.analyze_url
     * 创建时间 : 2018-07-18 15:24:03
     */
    private String analyzeUrl;

    /**
     * 习题答案(json数组),如果是判断题，right-对, wrong-错 -- exercise_info.answer
     * 创建时间 : 2018-07-18 15:24:03
     */
    private String answer;

    /**
     * 习题答案数据 -- exercise_info.answer_num
     * 创建时间 : 2018-07-18 15:24:03
     */
    private Byte answerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_info.create_time
     * 创建时间 : 2018-07-18 15:24:03
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_info.update_time
     * 创建时间 : 2018-07-18 15:24:03
     */
    private Date updateTime;

    /**
     * 是否删除（0-否 1-是） -- exercise_info.del_flag
     * 创建时间 : 2018-07-18 15:24:03
     */
    private Boolean delFlag;

    /**
     * exercise_info表的操作属性:serialVersionUID
     * 创建时间 : 2018-07-18 15:24:03
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 exercise_info.id的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 exercise_info.id的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 exercise_info.teacher_id的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * 数据字段 exercise_info.teacher_id的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * 数据字段 exercise_info.type的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public Byte getType() {
        return type;
    }

    /**
     * 数据字段 exercise_info.type的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * 数据字段 exercise_info.content_url的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public String getContentUrl() {
        return contentUrl;
    }

    /**
     * 数据字段 exercise_info.content_url的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl == null ? null : contentUrl.trim();
    }

    /**
     * 数据字段 exercise_info.analyze_url的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public String getAnalyzeUrl() {
        return analyzeUrl;
    }

    /**
     * 数据字段 exercise_info.analyze_url的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setAnalyzeUrl(String analyzeUrl) {
        this.analyzeUrl = analyzeUrl == null ? null : analyzeUrl.trim();
    }

    /**
     * 数据字段 exercise_info.answer的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * 数据字段 exercise_info.answer的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * 数据字段 exercise_info.answer_num的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public Byte getAnswerNum() {
        return answerNum;
    }

    /**
     * 数据字段 exercise_info.answer_num的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setAnswerNum(Byte answerNum) {
        this.answerNum = answerNum;
    }

    /**
     * 数据字段 exercise_info.create_time的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 数据字段 exercise_info.create_time的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 数据字段 exercise_info.update_time的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 数据字段 exercise_info.update_time的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 数据字段 exercise_info.del_flag的get方法 
     * 创建时间 : 2018-07-18 15:24:03
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * 数据字段 exercise_info.del_flag的set方法
     * 创建时间 : 2018-07-18 15:24:03
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}